@baseUrl = http://localhost:9080
@categoryId = 223e0158-d3a0-444d-8c1f-dfc55af5fa71

### Get all categories
GET {{baseUrl}}/api/categories

### Get a category by ID
GET {{baseUrl}}/api/categories/{{categoryId}}

### Create a new category
POST {{baseUrl}}/api/categories
Content-Type: application/json

{
  "name": "Family Vacation",
  "description": "Two-week family trip to the coast."
}

### Update a category
PUT {{baseUrl}}/api/categories/{{categoryId}}
Content-Type: application/json

{
  "name": "Friends",
  "description": "Weekend getaway with friends."
}

### Delete a category
DELETE {{baseUrl}}/api/categories/{{categoryId}}
