@baseUrl = http://localhost:9080
@categoryId = c2ac24ab-a565-4a55-936c-25ffbec7dc32

### Get all categories (authenticated user john)
GET {{baseUrl}}/api/categories
Authorization: Basic john john123

### Get all categories (authenticated user admin)
GET {{baseUrl}}/api/categories
Authorization: Basic admin admin123

### Get a category by ID (authenticated user)
GET {{baseUrl}}/api/categories/{{categoryId}}
Authorization: Basic john john123

### Create a new category (ADMIN ONLY)
POST {{baseUrl}}/api/categories
Content-Type: application/json
Authorization: Basic admin admin123

{
  "name": "Family Vacation",
  "description": "Two-week family trip to the coast."
}

### Update a category (ADMIN ONLY)
PUT {{baseUrl}}/api/categories/{{categoryId}}
Content-Type: application/json
Authorization: Basic admin admin123

{
  "name": "Friends",
  "description": "Weekend getaway with friends."
}

### Delete a category (ADMIN ONLY)
DELETE {{baseUrl}}/api/categories/{{categoryId}}
Authorization: Basic admin admin123
