@userId = 9ab24b75-76db-41b1-aa83-8c3992b894d0

### Get all users
GET http://localhost:9080/api/users

### Gets a user by their ID
GET http://localhost:9080/api/users/{{userId}}

### Get trips for a specific user
GET http://localhost:9080/api/users/{{userId}}/trips

### Register a new user (Create)
POST http://localhost:9080/api/users
Content-Type: application/json

{
  "login": "newuser",
  "dateOfBirth": "1995-03-20"
}

### Update a user
PUT http://localhost:9080/api/users/{{userId}}
Content-Type: application/json

{
  "login": "andy",
  "dateOfBirth": "1985-10-30"
}

### Deletes a user
DELETE http://localhost:9080/api/users/{{userId}}
