
### Get all users
GET http://localhost:9080/api/users

### Gets a user by their ID
GET http://localhost:9080/api/users/a252f148-2664-4ed1-b195-d44b0bb6d886

### Create a new user
PUT http://localhost:9080/api/users
Content-Type: application/json

{
  "login": "Jan Kowalski",
  "dateOfBirth": "1990-05-15"
}

### Update a user
PUT http://localhost:9080/api/users/a252f148-2664-4ed1-b195-d44b0bb6d886
Content-Type: application/json

{
  "login": "andrew",
  "dateOfBirth": "1985-10-30"
}

### Deletes a user
DELETE http://localhost:9080/api/users/a252f148-2664-4ed1-b195-d44b0bb6d886

### Get avatar
GET http://localhost:9080/api/avatars/a252f148-2664-4ed1-b195-d44b0bb6d886.png

### Delete avatar
DELETE http://localhost:9080/api/avatars/a252f148-2664-4ed1-b195-d44b0bb6d886.png

### Upload/Update avatar
# in request body provide new name of the image
# image to upload should be in ./resources/avatars directory
PUT http://localhost:9080/api/avatars/a252f148-2664-4ed1-b195-d44b0bb6d886.png
Content-Type: image/png

< ./resources/avatars/avatar5.png